version: '3.7'
services:
  redis:
    image: redislabs/redisgraph
    hostname: redis
    ports:
      - "6379:6379"
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ameli_db
    ports:
      - "5433:5432"
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: root
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"